version: "3.8"
services:
        api:
                container_name: wedemy_api
                build:
                        context: .
                        dockerfile: Dockerfile-backend
                ports:
                        - "8080:8080"
                depends_on:
                        - postgres

        web:
                container_name: wedemy_web
                build:
                        context: .
                        dockerfile: Dockerfile-frontend
                expose:
                        - "80"
                ports:
                        - "80:80"
        postgres:
                container_name: wedemy_pg
                image: postgres:13.2-alpine
                volumes:
                        - ./wedemy.sql:/docker-entrypoint-initdb.d/wedemy.sql
                environment:
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_DB=wedemy
                expose:
                        - "5435"
                ports:
                        - "5435:5435"
                command: -p 5435
networks:
        default:
                name: "wedemy_network"
