version: "3.7"
services:
        api:
                container_name: wedemy_api
                build:
                        context: .
                        dockerfile: Dockerfile-backend2
                ports:
                        - "9090:8080"
                depends_on:
                        - postgres

        web:
                container_name: wedemy_web
                build:
                        context: .
                        dockerfile: Dockerfile-frontend                         
                ports:
                        - "4200:4200"

        postgres:
                container_name: wedemy_pg
                image: postgres:13.2-alpine
                volumes:
                        - ./wedemy.sql:/docker-entrypoint-initdb.d/wedemy.sql
                environment:
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_DB=wedemy                
                ports:
                        - "5435:5432"     
                                   
networks:
        default:
                name: "wedemy_network"
