version: "3.7"
services:
        api:
                container_name: w_api
                image: lawencon05/wedemy_api:1.1                
                ports:
                        - "9090:8080"
                depends_on:
                        - db

        web:
                container_name: w_web
                image: lawencon05/wedemy_web:1.0              
                ports:
                        - "90:80"

        db:
                container_name: w_db
                image: lawencon05/wedemy_db:1.0               
                ports:
                        - "5435:5432"

networks:
        default:
                name: "wedemy_network"
