version: "3.7"
services:
        api:
                container_name: w_api
                build:
                        context: .
                        dockerfile: Dockerfile-backend
                ports:
                        - "9090:8080"
                depends_on:
                        - db

        web:
                container_name: w_web
                build:
                        context: .
                        dockerfile: Dockerfile-frontend
                ports:
                        - "4200:4200"

        db:
                container_name: w_db
                build:
                        context: .
                        dockerfile: Dockerfile-db
                ports:
                        - "5435:5432"

networks:
        default:
                name: "wedemy_network"
