FROM adoptopenjdk/maven-openjdk11

ENV HOST_POSTGRES=w_db
ENV PORT_POSTGRES=5432
ENV DB_POSTGRES=wedemy
ENV USERNAME_POSTGRES=postgres
ENV PASSWORD_POSTGRES=postgres

WORKDIR /apps

COPY wedemy_backend/ .

RUN mvn clean package -DskipTests

CMD ["java", "-jar", "/apps/elearning/target/elearning-0.0.1-SNAPSHOT.jar"]